package Globals

import Plugins.CommonUtils.Hub.ServiceCenter.displayCode
import Plugins.CommonUtils.StringUtils

object GlobalStrings {
  val serviceCode: String = displayCode
  /** 工作目录 */
  val workingDir: String =System.getProperty("user.dir")
  /** 放treeObject的文件夹位置 */
  val treeObjectFolder : String = workingDir + StringUtils.slash + "tree-object" + StringUtils.slash

  val serverPublic:String="MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7Hel5OXFIVk2ed9nzyqyvjBKQzPGVRLCZOxZDSu5WS2q/UbsWeqT2X07zTZknW1Dhyb4U3PFpr1kLivK+hVecVv3f6N96NU7GXk6dXlnrJ4zdclUKtQUJKfkZPOJznrrH+erZQFl+NsfxzJWXeJDvakHdhOjD9xBtlVExpzcZgwIDAQAB"
  val clientPrivate:String="MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJqO6+AJD5MWIaaBj/nSLipPdqoUOZLpWkRn9wjUR+hXc6HIWPJA8RD3agyvLgTObXX1zgPUawOhHKhb/Esuny8AV0Ex9boB0Qu1P9iX7imFxzfUea0BtBHY1MXawIlm5kuN7Ks8wog1/zRvma6cdOLKqdII1X7Ay3dK0RHCxUrvAgMBAAECgYEAizU3Vm5SzNQeMu53UzfvxMQVyVK2GJB9cSeC5TzuF2LND2Z4VpoPhoyRxCL0e/fBt4FRsTlducMfILTZJI41aKROCr2jqVDKbvg0vyIm7RnV2AhJ1/j28Zk3Ed5RYe9AoBkCtLHt9zmHgraRuleu28L8lb+ghjL6z0NhEpXnw8ECQQDZlRIc3fCXSMWmpDMQZ6rw2xOu0kE9/G8Vi26KTkD5/EoBZROL7FnDLNsdM7MbLCAKYzbASN7+aGmNaR+xQMfJAkEAtdkat7MoRXqNe8LNn+y12SNeQKxu7U3xRyBIdWZ30Q0e4HaISINti1bm0WqTXFQS6COqRVj0ZqFtIBh8DnRI9wJAHaXEXA6Z0+NkmzpQgvG9Ryhy3CVmIm4dLNBc9ZeIHwgThXEiYrSH3qJkEOyUgSVYEFJIiZbkW8Iab9xdJyfukQJATg5h1IZXe/NN9di5cLMnn4v58iLR/pSdQ52M3K/eMGLEZS8b8pxPkib8LtnjZRdFglWEyf2T8tXJxKQd5ApwIwJARhxrDNAUex7UsTTcrUNMvVVQ/CAyuBPxS1h+g4FOI7iTsZWUyiNJQ/ZUgSq6oTVeiNrK95pPr2clWFJQmuCxLQ=="

}
